name: New DBT
output: results
dataset: dbt
dimension: 52x52
size:
  train: 20000
  test: 5000
about: Testando processar os dados para redes neurais com normalização entre 0 e 1 e para os tradicionais apenas dividir por 255.
normalize: True
shuffle: True