name: New Gaussian 1
output: results
dataset: BSD300
dimension: 52x52
size: 30000
about: Testando processar os dados para redes neurais com normalização entre 0 e 1 e para os tradicionais apenas dividir por 255.
noise:
  type: gaussian
  mean: 0.0
  variance: 0.01
normalize: True
shuffle: True